### ISSUE TITLE
Setting of max_it using "QPSSetTolerances" does not work

### ISSUE THREAD

**Issue by lukaspospisil** [It4innovations/permon#4] opened 2017-02-28 20:23 UTC
Hi guys,

I am trying to set max_it of QPS in my code (not from console neither using flloprc), but it seems that it does not work. Here is part of my C++ code:

```
coutMaster << "TEST1: " << this->maxit << std::endl;
TRYCXX( QPSCreate(PETSC_COMM_WORLD, &qps) );
TRYCXX( QPSSetQP(qps, qp) );
TRYCXX( QPSSetTolerances(qps, this->eps, this->eps, 1e12, this->maxit) );
TRYCXX( QPSMonitorSet(qps,QPSMonitorDefault,NULL,0) );
TRYCXX( QPSetRhs(qp, b) );
TRYCXX( QPTFromOptions(qp) ); 
TRYCXX( QPSSetFromOptions(qps) );
TRYCXX( QPSSetUp(qps) ); 

int maxit2;
TRYCXX( QPSGetTolerances(qps,PETSC_NULL,PETSC_NULL,PETSC_NULL, &maxit2) );
coutMaster << "TEST2: " << maxit2 << std::endl;
```

and it produces
```
TEST1: 1000
TEST2: 100
```

Is there any difference between setting the max_it of inner/outer solver? How can I set the number of iterations of outer solver from the code?

Thanks a lot, LP

**Comment by lukaspospisil** [comment] 2017-02-28 20:28
When I run the code with `-qps_max_it 1234`, the output is changed to
```
TEST1: 1000
TEST2: 1234
```
and value from `QPSSetTolerances` is still ignored.

**Comment by haplav** [comment] 2017-02-28 20:52
Hi Lukas!
If you use SMALXE, `-qps_max_it` sets the maximum number of outer iterations whereas the maximum number of inner iterations is controlled by `-smalxe_qps_max_it`. The inner solver gets `smalxe_` prefix which is perhaps misleading. The values from the command line should always precede those in flloprc, and these precede those set programatically. Hence, the first case looks to me like a bug but the second not. I will look at it.

**Comment by haplav** [comment] 2017-02-28 21:21
What you set by `QPSSetTolerances` is the maximum iteration count for the outer solver. E.g. for SMALXE+MPGP, it is SMALXE. For MPGP only, it is MPGP. There is currently no function to get the inner solver. I will add one.

I'm so far not able to reproduce the first case. Please make sure you don't pass `-qps_max_it` to QPS via `flloprc`.

**Comment by lukaspospisil** [comment] 2017-02-28 21:39
Got it! It seems that it depends on the order of commands:

(wrong - does not set maxit):
```
QPSSetTolerances
QPSSetFromOptions
```

(right - sets maxit ):
```
QPSSetFromOptions
QPSSetTolerances
```

I don't know if it is bug, or my fault with wrong order.

**Comment by haplav** [comment] 2017-02-28 21:48
It depends on what you want :-) But typically you first set your program's defaults programatically (`QPSSetTolerances`) and then you have a chance to override these defaults from rc file or command line (`QPSSetFromOptions `). This gives you more flexibility without needing to recompile when the parameter needs to be changed. PETSc behaves the same way.

**Comment by haplav** [comment] 2017-02-28 22:04
The "wrong order"
```
QPSSetTolerances
QPSSetFromOptions
```
 should work as you expect (preserve your maxit set in the program) provided you don't pass
```
-qps_max_it 100
```
anyhow.

**Comment by haplav** [comment] 2017-03-07 21:17
Hi Lukas,
can I close this, please?
Thanks,
Vaclav

**Comment by lukaspospisil** [comment] 2017-03-08 13:52
Hi Vaclav,

of course, the behaviour is quite clear right now. It depends on what user wants to set and what has larger "importance" - if values from console or values provided by code.

Thanks,
Lukas

**Comment by haplav** [comment] 2017-03-08 15:16
Thanks, closing.

**Closed as completed by haplav** 2017-03-08 15:16 UTC
